# These are supported funding model platforms

github: [omeans-team]
#patreon: omeanspatreon
#open_collective: omeanscollective
#ko_fi: omeansko-fi
#tidelift: npm/omeans-package
#community_bridge: cloud-foundry-omeans
#liberapay: omeansliberapay
#issuehunt: omeansissuehunt
#lfx_crowdfunding: cloud-foundry-omeans-lfx
#polar: omeanspolar
buy_me_a_coffee: omeansteam
#thanks_dev: omeansthanksdev
#custom: ['https://www.omeans.com/donate', 'https://omeans-team.github.io/sponsor']
